### ISSUE TITLE
Panels applied for tiering with version to be included into the summary of findings

### ISSUE THREAD

**Issue by arendon** [genomicsengland/GelReportModels#22]
To pull out of the tiering the panels applied and to include it the ClinicalReportRD as part of the methods

**Comment by Antonior26** [comment]
Panels applied are explicitly specified in the Interpretation request (at the family level) it will pulled when the Clinical Report is generated. ClinicalReportRD only contains the information that we don't have yet.

**Comment by oak888** [comment]
Is it just me but why are we not just having this all as part of the
interpretation genome as non mandatory  (instead of two models) and then
apply two different validations at each stage...

**Comment by Antonior26** [comment]
@oak888, That would not match at all with the philosophy of these models, we try to reuse as much as we can, but if they have different mandatory fields are different models. We can rethink that but I am quite convinced they need to be 2 separated models, for 2 very different purposes.

**Comment by oak888** [comment]
Ok.
Eik
