### ISSUE TITLE
Rrecommended way to install the GelReportModels package

### ISSUE THREAD

**Issue by andyb3** [genomicsengland/GelReportModels#421]
What is the current recommended way to install the GelReportModels package? Previously I installed using the following steps:

```
git clone git@github.com:genomicsengland/GelReportModels.git
cd GelReportModels
pip install -r requirements.txt
python build.py --skip-docs --skip-java
pip install . 
```

But I can't see the `requirements.txt` file in the latest version (although it is still referenced in the installation instructions in the README and [here](https://gelreportmodels.genomicsengland.co.uk/#installation)) . 

Can I install using the setup.py script ( `python setup.py install`)?

Many thanks,
Andy

**Comment by greglever** [comment]
@andyb3 what happens when you try:
```
pip install .
python build.py --skip-docs --skip-hava
```
?

**Comment by andyb3** [comment]
Success! Thanks very much
